<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-27T19:59:28 IST" name="Default suite" finished-at="2025-01-27T19:59:28 IST" duration-ms="74">
    <groups>
    </groups>
    <test started-at="2025-01-27T19:59:28 IST" name="Default test" finished-at="2025-01-27T19:59:28 IST" duration-ms="74">
      <class name="TestNgDemo.ddf">
        <test-method signature="test1()[pri:0, instance:TestNgDemo.ddf@74f0ea28]" started-at="2025-01-27T19:59:28 IST" name="test1" finished-at="2025-01-27T19:59:28 IST" duration-ms="19" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
The exception was thrown with the wrong message: expected "Testing failed" but got "expected [2] but found [1]"]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
The exception was thrown with the wrong message: expected "Testing failed" but got "expected [2] but found [1]"
at org.testng.internal.invokers.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:69)
at org.testng.internal.invokers.TestInvoker.considerExceptionsInternal(TestInvoker.java:885)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:860)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:741)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.AssertionError: expected [2] but found [1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at TestNgDemo.ddf.test1(ddf.java:12)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test2()[pri:1, instance:TestNgDemo.ddf@74f0ea28]" started-at="2025-01-27T19:59:28 IST" name="test2" finished-at="2025-01-27T19:59:28 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- TestNgDemo.ddf -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
